#
# Copyright 2024 CAPECCHI SPA
# Generated by: Fusion 1.0   01/10/2024
# Update:       24/02/2025
# Author:       Daniele Speziale
# Filename:     app.py
# Description:  Blueprint Support
# Style Guide:  PEP8
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
import atexit
import decimal
import http
import json
import os
import socket
import threading
import time
from datetime import datetime, timedelta
import logging

import requests
from apscheduler.schedulers.background import BackgroundScheduler

from flask import Flask, session, send_from_directory, render_template
from flask_sqlalchemy import SQLAlchemy
from flask_session import Session

from sqlalchemy import MetaData
from svgwrite.data.svgparser import seconds

import DB

from blueprints.auth import auth_bp


from config import Config

app = Flask(__name__)
app.secret_key = 'chiave_super_segreta'











# Registriamo i Blueprint
app.register_blueprint(auth_bp)




@app.after_request
def after_request(response):
    response.headers.add('Access-Control-Allow-Origin', '*')
    response.headers.add('Access-Control-Allow-Headers', 'Content-Type,Authorization')
    response.headers.add('Access-Control-Allow-Methods', 'GET,PUT,POST,DELETE,OPTIONS')
    return response


if __name__ == '__main__':
    if socket.gethostname()=='PC-SPEZIALE':

        app.run(host='0.0.0.0', port=80, debug=True)
    else:
        app.run(host='0.0.0.0', port=80)